title: Code of Conduct
description: Responsible for enforcing AMP's Code of Conduct. (The Technical Steering Committee delegates its responsibility for enforcement of the Code of Conduct to this Working Group.)
facilitator:
  login: nainar
  name: Naina Raisinghani
members:
  - login: nainar
    name: Naina Raisinghani
  - login: danielrozenberg
    name: Daniel Rozenberg
  - login: estherkim
    name: Esther Kim
  - login: jpettitt
    name: John Pettitt
